version: '3.7'

volumes:
  minoapp-www-data:
    name: minoapp-www-data
  minoapp-mysql-data:
    name: minoapp-mysql-data

services:
  minoapp-db:
    image: mariadb:10.7-focal
    container_name: minoapp_mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - minoapp-mysql-data:/var/lib/mysql
    mem_limit: 2G
    cpus: '2'
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD 
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    restart: unless-stopped
    networks:
      - ghost
    labels:
      - "traefik.enable=false"

  minoapp_ghost:
    image: ghost:5
    container_name: minoapp_ghost
    restart: unless-stopped
    expose:
      - 2368
    links :
      - minoapp-db
    networks:
      - web
      - ghost
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:minoapp.com"

      - "traefik.docker.network=web"
      - "traefik.http.services.minoapp_ghost.loadbalancer.server.port=2368"
    volumes:
      - minoapp-www-data:/var/lib/ghost/content
    depends_on:
      - minoapp-db
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: minoapp-db
      database__connection__user: $MYSQL_USER
      database__connection__password: $MYSQL_PASSWORD
      database__connection__database: $MYSQL_DATABASE
      url: https://minoapp.com
      NODE_ENV: production
    

networks:
  ghost :
    name: ghost
  web:
    external: true
